### ISSUE TITLE
Change project directory structure

### ISSUE THREAD

**Issue by ubis** [DignityTeam/Minerva#13]
Current directory structure is kinda messy: we have bin folder, but we don't push binaries to repo.
To change that, we could use a little bit changed structure:

- /src - keep as is;

- /lib - keep as is;

- /tools - keep as is;

- /doc - move all documentation, configs, game data(XML's), etc... there.

Inside **/doc** could be:

- /doc/sql - all database SQL files;

- /doc/conf - all configuration files;

- /doc/data - all game data(XML's and so on);

- /doc/... - something else, documentation.

**Comment by emi58** [comment]
We should never ever push binaries to git.
agree with this exception: /config should be the place where we put the config

**Comment by allocenx** [comment]
I agree.

**Comment by Stricted** [comment]
i agree too, its really a mess right now

**Comment by lKnuckles** [comment]
i agree

**Comment by G0ldenheaven** [comment]
Lol u setuped the new struct folder and I'm fine with a doc folder so I agree as well
